version: '3.1'

services:
  sqlserver:
    build: .
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

volumes:
  sqlserverdata:
